version: '2'

services:

  reverse-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/conf:/etc/nginx/conf.d
      - ./data/vhost:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/dhparam:/etc/nginx/dhparam
      - ./data/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  reverse-proxy-le:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    container_name: nginx-proxy-le
    depends_on:
      - reverse-proxy
    volumes_from:
      - reverse-proxy
    volumes:
      - ./data/certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

networks:
  default:
    external:
      name: reverse-proxy-net