version: '3'
services:

  reverse-proxy:
    image: nginx:1.17.8-alpine
    container_name: reverse-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PROXY_PATH}/data/conf.d:/etc/nginx/conf.d
      - ${PROXY_PATH}/data/vhost.d:/etc/nginx/vhost.d
      - ${PROXY_PATH}/data/html:/usr/share/nginx/html
      - ${PROXY_PATH}/data/certs:/etc/nginx/certs:ro

  reverse-proxy-gen:
    image: jwilder/docker-gen:0.7.3
    command: -notify-sighup reverse-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: reverse-proxy-gen
    depends_on:
      - reverse-proxy
    restart: always
    volumes:
      - ${PROXY_PATH}/data/conf.d:/etc/nginx/conf.d
      - ${PROXY_PATH}/data/vhost.d:/etc/nginx/vhost.d
      - ${PROXY_PATH}/data/html:/usr/share/nginx/html
      - ${PROXY_PATH}/data/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${PROXY_PATH}/data/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  reverse-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12
    container_name: reverse-proxy-letsencrypt
    depends_on:
      - reverse-proxy
      - reverse-proxy-gen
    restart: always
    volumes:
      - ${PROXY_PATH}/data/conf.d:/etc/nginx/conf.d
      - ${PROXY_PATH}/data/vhost.d:/etc/nginx/vhost.d
      - ${PROXY_PATH}/data/html:/usr/share/nginx/html
      - ${PROXY_PATH}/data/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: reverse-proxy
      NGINX_DOCKER_GEN_CONTAINER: reverse-proxy-gen

networks:
  default:
    external:
      name: reverse-proxy-net